Pet-Hotel/Models/Pet.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pet_Hotel.Models
{
    public class Pet
    {
        
        public int Id { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$",
               ErrorMessage = "Invalid pet name! Pet name should contain only alphabets!")]
        public string Name { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$",
              ErrorMessage = "Invalid pet type! Pet type should contain only alphabets!")]
        public string Type { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$",
              ErrorMessage = "Invalid pet breed! Pet breed should contain only alphabets!")]
        public string Breed { get; set; }

        [Range(1,20)]
        public int Age { get; set; }

        [Required]
        [Display(Name="Pet Owner")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", 
            ErrorMessage = "Invalid pet owner name! Pet owner name should contain only alphabets!")]
        public string PetOwner { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name ="Checked In")]
        public DateTime checkedIn { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Checked Out")]
        public DateTime? checkedOut { get; set; }  
    }
}

Pet-Hotel/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pet_Hotel.Data;
using Pet_Hotel.Models;

namespace Pet_Hotel.Controllers
{
    public class PetsController : Controller
    {
        private readonly Pet_HotelContext _context;

        public PetsController(Pet_HotelContext context)
        {
            _context = context;
        }

        // GET: Pets
        public async Task<IActionResult> Index(string petType, string searchName,
                                               string searchBreed,string searchPetOwner)
        {
            var pets = from p in _context.Pet
                       select p;

            // LINQ query that retrieves all the pet types from the database.
            IQueryable<string> petTypeQuery = from p in _context.Pet
                                            orderby p.Type
                                            select p.Type;

            // name
            if (!string.IsNullOrEmpty(searchName))
            {
                pets = pets.Where(x => x.Name!.Contains(searchName));
            }

            // breed
            if (!string.IsNullOrEmpty(searchBreed))
            {
                pets = pets.Where(x => x.Breed!.Contains(searchBreed));
            }

            // pet owner
            if (!String.IsNullOrEmpty(searchPetOwner))
            {
                pets = pets.Where(x => x.PetOwner!.Contains(searchPetOwner));
            }

            // pet type
            if (!String.IsNullOrEmpty(petType))
            {
                pets = pets.Where(x => x.Type == petType);
            }

            var petTypeVM = new PetTypeViewModel
            {
                Types = new SelectList(await petTypeQuery.Distinct().ToListAsync()),
                Pets = await pets.ToListAsync()
            };

            
            return View(petTypeVM);
        }

        // GET: Pets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pet == null)
            {
                return NotFound();
            }

            var pet = await _context.Pet
                .FirstOrDefaultAsync(m => m.Id == id);

            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // GET: Pets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Type,Breed,Age,PetOwner,checkedIn,checkedOut")] Pet pet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(pet);
        }

        // GET: Pets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pet == null)
            {
                return NotFound();
            }

            var pet = await _context.Pet.FindAsync(id);
            if (pet == null)
            {
                return NotFound();
            }
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Breed,Age,PetOwner,checkedIn,checkedOut")] Pet pet)
        {
            if (id != pet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetExists(pet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pet);
        }

        // GET: Pets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pet == null)
            {
                return NotFound();
            }

            var pet = await _context.Pet
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pet == null)
            {
                return Problem("Entity set 'Pet_HotelContext.Pet'  is null.");
            }
            var pet = await _context.Pet.FindAsync(id);
            if (pet != null)
            {
                _context.Pet.Remove(pet);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PetExists(int id)
        {
          return (_context.Pet?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pet-Hotel/Views/Pets/Create.cshtml
@model Pet_Hotel.Models.Pet

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Breed" class="control-label"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PetOwner" class="control-label"></label>
                <input asp-for="PetOwner" class="form-control" />
                <span asp-validation-for="PetOwner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="checkedIn" class="control-label"></label>
                <input asp-for="checkedIn" class="form-control" />
                <span asp-validation-for="checkedIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="checkedOut" class="control-label"></label>
                <input asp-for="checkedOut" class="form-control" />
                <span asp-validation-for="checkedOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pet-Hotel/Views/Pets/Delete.cshtml
@model Pet_Hotel.Models.Pet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PetOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PetOwner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.checkedIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.checkedIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.checkedOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.checkedOut)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Pet-Hotel/Views/Pets/Details.cshtml
@model Pet_Hotel.Models.Pet

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PetOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PetOwner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.checkedIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.checkedIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.checkedOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.checkedOut)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Pet-Hotel/Views/Pets/Edit.cshtml
@model Pet_Hotel.Models.Pet

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Breed" class="control-label"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PetOwner" class="control-label"></label>
                <input asp-for="PetOwner" class="form-control" />
                <span asp-validation-for="PetOwner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="checkedIn" class="control-label"></label>
                <input asp-for="checkedIn" class="form-control" />
                <span asp-validation-for="checkedIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="checkedOut" class="control-label"></label>
                <input asp-for="checkedOut" class="form-control" />
                <span asp-validation-for="checkedOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pet-Hotel/Views/Pets/Index.cshtml
@model Pet_Hotel.Models.PetTypeViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Pets</h1>
<style>
   .myEditBtn {
  color: black;  
  border: 2px solid #949494;
   background-color: #b8dcf8!important;
  border-radius: 30px;
  padding: 3px 18px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  }
  .myDetailsBtn {
  color: black;  
  border: 2px solid #949494;
   background-color:#b2ffb9!important;
  border-radius: 30px;
  padding: 2px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  }
  .myDeleteBtn {
  color: black;  
  border: 2px solid #949494;
   background-color:  #ff7a7a!important;
  border-radius: 30px;
  padding: 2px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}
</style>

<p>
    <a asp-action="Create"; class="myEditBtn">Add new pet</a>
</p>
<form asp-controller="Pets" asp-action="Index" method="get">
    <p>
        <!--Pet Type-->
        <select asp-for="PetType" asp-items="Model.Types">
            <option value="">All Pets</option>
        </select>

        <!--Pet Name-->
        Name: <input type="text" asp-for="SearchName" />
         <input type="submit" value="Filter" />

         <!--Pet Breed-->
           Breed: <input type="text" asp-for="SearchBreed" />
        <input type="submit" value="Filter" />

        <!--Pet Owner-->
        Pet Owner: <input type="text" asp-for="SearchPetOwner" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].Name)
             </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].Breed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].PetOwner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].checkedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pets[0].checkedOut)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Pets) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Breed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PetOwner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.checkedIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.checkedOut)
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="myEditBtn">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id"  class="myDetailsBtn">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id"  class="myDeleteBtn">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>